name: Build macOS Release

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
          fetch-depth: 0

      - name: Install dependencies
        run: |
          brew update
          brew install cmake ninja

      - name: Create build directory
        run: mkdir -p build

      - name: Configure CMake
        working-directory: ./build
        run: cmake .. -G Ninja -DCMAKE_BUILD_TYPE=Release -DUSE_SANITIZER=OFF -DBUILD_TESTS=ON

      - name: Build spectrum_clap target
        working-directory: ./build
        run: cmake --build . --target spectrum_clap --config Release

      - name: Build spectrum_test_runner target
        working-directory: ./build
        run: cmake --build . --target spectrum_test_runner --config Release

      - name: Run tests 10 times
        working-directory: ./build
        run: |
          for i in {1..10}; do
            echo "Test run $i of 10"
            ./spectrum_test_runner
          done