name: Build macOS Release

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
          fetch-depth: 0

      - name: Create build directory
        run: mkdir -p build

      - name: Build and test
        working-directory: ./build
        run: |
          cmake .. -G Ninja -DCMAKE_BUILD_TYPE=Release -DUSE_SANITIZER=OFF -DBUILD_PLUGIN=ON -DBUILD_TESTS=ON
          cmake --build . --target spectrum-analyzer-processor --config Release
          cmake --build . --target spectrum_test_runner --config Release
          for i in {1..10}; do
            echo "Test run $i of 10"
            ./spectrum_test_runner
          done
          cmake --build . --target spectrum_clap --config Release